# Uncomment the next line to define a global platform for your project
platform :ios, '16.6'

target 'IntestinesSupport' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  pod 'FSCalendar'
  pod 'DGCharts'

  # Pods for IntestinesSupport

  target 'IntestinesSupportTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IntestinesSupportUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.6'
    end
  end
end