# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IntestinesSupport' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  pod 'FSCalendar'

  # Pods for IntestinesSupport

  target 'IntestinesSupportTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IntestinesSupportUITests' do
    # Pods for testing
  end

end
